### ISSUE TITLE
Simplify cgtd to be only mutable operations on ipfs

### ISSUE THREAD

**Issue by rcurrie** [ga4gh/cgtd#11]
Currently cgtd provides three things:
- Mutable operations on cgt/ipfs (make a submissions, add a peer)
- Convenience operations on cgt (recursively find all submissions for all peers) 
- HTML GUI to cgt

I think we should simplify cgt to be purely the mutable operations. The actual content would then be directly accessed in ipfs from external applications. cgtd would listen on a specific port much like ipfs does on 5001 for mutable operations and everything else would be purely accessing ipfs directly with the knowledge of the structure of a submission (json with fields and files).

Part of my motivation is informed after working on a search engine for cgt based on elastic search. Going through cgtd to get to the data didn't seem to add any value which lead me to believe it wasn't really adding value (the read only operations that is). Also by moving to a specific port it will allow you to mutate cgtd from a machine without shelling into the actual docker while still blocking that port from external access.

For the HTML gui's those should really just be published to ipfs itself and be purely client side browsing/access of ipfs.

**Comment by brainstorm** [comment]
From the beginning of this project I thought about CGT as a lightweight abstraction of IPFS for life science practitioners.

I see your point as an optimization, since as you mentioned a few times, there's not much value of passing data through a (potentially slow, hard to scale) python reference implementation. So thumbs up for your thinking on limiting CGT to [**CRUD** operations](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) (mutable/immutable for me is close to the functional programming paradigms/domains and such, not web APIs like we are talking in here).

So following this, IMHO, the HTML GUI should be factored out as an app/plugin instead of having it in core.

Also, I would totally recommend scanning this website before expanding the CGT API any further:

http://apistylebook.com/

Cheers!

@ohofmann

**Comment by rcurrie** [comment]
After discussion at ga4gh this seems a bit premature as ipfs hasn't been vetted completely (though it still looks like the best candidate). So for now leaving in the simple UI makes sense. Also some of the convenience functions are effectively moved to apps (tree traversal for example)
